### ISSUE TITLE
Rust: `interface transitively depends on an interface in incompatible ways`

### ISSUE THREAD

**Issue by rvolosatovs** [bytecodealliance/wit-bindgen#1043]
Given following WIT:
```wit
package repro:component@0.1.0;

world component {
    export wasi:io/poll@0.2.1;
    export wasi:http/types@0.2.1;
}
```

And following `lib.rs`:

```rust
mod bindings {
    use super::Component;

    wit_bindgen::generate!({ generate_all });

    export!(Component);
}

pub struct Component;
```

`wit-bindgen 0.30` crate fails with:
```
error: failed to resolve directory while parsing WIT for path [/private/tmp/component/wit]
       
       Caused by:
         interface transitively depends on an interface in incompatible ways
            --> /private/tmp/component/wit/component.wit:37:22
             |
          37 |     export wasi:http/types@0.2.1;
             |                      ^----
 --> src/lib.rs:4:5
  |
4 |     wit_bindgen::generate!({ generate_all });
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `wit_bindgen::generate` (in Nightly builds, run with -Z macro-backtrace for more info)
```

The complete reproducer is available at https://github.com/rvolosatovs/wit-bindgen-export-bug-repro

Most likely refs https://github.com/WebAssembly/component-model/issues/208

**Comment by rvolosatovs** [comment]
This seems to work for https://github.com/bytecodealliance/WASI-Virt

https://github.com/bytecodealliance/WASI-Virt/blob/c4512614d0bbe50044b93577099232c1701b06e2/virtual-adapter/src/lib.rs#L9-L13
https://github.com/bytecodealliance/WASI-Virt/blob/c4512614d0bbe50044b93577099232c1701b06e2/wit/virt.wit#L5-L46

**Comment by alexcrichton** [comment]
I responded a bit on [Zulip](https://bytecodealliance.zulipchat.com/#narrow/stream/327223-wit-bindgen/topic/Re-exporting.20host.20exports.20from.20a.20component/near/466098800) as well but the problem here is that `wasi:http/types` transitively depends on `wasi:io/streams` which then also depends on `wasi:io/poll`. That means that the `wasi:io/poll` that `wasi:http/types` refers to is implicitly an import, but it's also an export here. That means that it's both an export and an import, which causes this conflict (and known bad error message).

The fix for now is to export more interfaces, for example `wasi:io/streams` here too. I believe that's how wasi-virt works by exporting everything.
