### ISSUE TITLE
Use build script instead of `wasm-tools` cli in the README example

### ISSUE THREAD

**Issue by HKalbasi** [bytecodealliance/wit-bindgen#1066]
If I understand correctly, `wasm-tools component new` uses `wit-component` crate under the hood, so we can use it in a `build.rs` directly. By using it, a single `cargo build` will produce the final wasm file and there is no need to install seperate cli components, so I think it makes the process a bit smoother.

**Comment by pchickey** [comment]
Rust 1.82 just launched support for `wasm32-wasip2` that includes wit-component as part of the linker so that it produces components - we were anticipating that, and it will become the recommended route once folks have enough time to update the docs. Rust blog post announcing that will go out today.

**Comment by HKalbasi** [comment]
Just used the `wasm32-wasip2`, and it works like a charm!
