### ISSUE TITLE
Add rust-wasm-js import support

### ISSUE THREAD

**Issue by quininer** [bytecodealliance/wit-bindgen#131]
When I tried to call another wasm module from wasm in browser, I noticed that I needed to call the js generated by `wit-bindgen`.
It works, but may have some performance flaws, such as when dealing with `String`, it needs to allocate memory at js layer, and one more extra utf8 check.

It would be nice if `wit-bindgen` could directly generate rust code to call the wasm module using `js-sys  crate.

**Comment by alexcrichton** [comment]
This is the eventual goal of the interface types proposal of WebAssembly, where you can directly link wasm components together and there won't be JS shims. For now there always has to be a JS shim to achieve the current semantics of interface types. Optimizing this will be possible over time, but for now further improvements for speed and such should primarily go to the interface types proposal rather than here I think.
