### ISSUE TITLE
Unable to use identifiers with leading underscores

### ISSUE THREAD

**Issue by Michael-F-Bryan** [bytecodealliance/wit-bindgen#168]
I'm trying to convert some hand-written host functions over to WIT files and ran into some issues writing declarations for a function that starts with an underscore. 

The original function looks something like this:

```rust
extern "C" {
  fn _debug(msg: *const u8, len: u32);
}
```

Doing the naive thing and declaring a function called `_debug` doesn't work because `_` isn't allowed in identifiers.

```text
Error: invalid character in identifier '_'
     --> runtime-v0.wit:15:1
      |
   15 | _debug: function(msg: string) -> u32
      | ^
```

Converting `_` to `-` and/or wrapping it in quotes results in a different error.

```text
Error: identifiers must have characters between '-'s
     --> runtime-v0.wit:15:1
      |
   15 | "-debug": function(msg: string) -> u32
      | ^
```

Do you have any suggestions for how I might be able to make this work, if at all possible?

**Comment by tschneidereit** [comment]
This will not work, because wit-bindgen requires a pretty strict naming scheme to ensure that the names can be mapped into idiomatic identifiers for as many languages as possible. E.g., `debug_function` would be mapped to `debug_function` in Rust, `debugFunction` in JS, and `DebugFunction` in C#, but it's not immediately clear what should happen with a leading `-`.

**Comment by Michael-F-Bryan** [comment]
Yeah, I had a feeling that would be the case. I might put `debug()` in the WIT file then patch the function name every time I regenerate bindings.
