### ISSUE TITLE
Accessing WebGPU via wit-defined library

### ISSUE THREAD

**Issue by lwansbrough** [bytecodealliance/wit-bindgen#175]
I'm curious if it would be possible (as of right now with present technology) to expose the WebGPU interface from a web browser to a program (ie. a WASM instance in a browser) through interface types.

I understand my question relates to this: https://github.com/bytecodealliance/wit-bindgen/issues/149

I would like to provide a runtime which exposes the GPU through a single interface (ie. `mylibrary::gpu` -- defined by a .wit/bindings) which guest programs can access without concern for the underlying host (ie. a browser or another native platform which implements WebGPU.)

**Comment by alexcrichton** [comment]
Personally I don't know anything about WebGPU, so I can't really answer any specifics here unfortunately.

Otherwise though the answer to this question is probably along the lines of "maybe?" depending on the exact shape of WebGPU APIs and the support for interface types in JS. It's certainly an aspiration of interface types that it would work for WebIDL-bound APIs like WebGPU, but the devil is always in the details.

I'm going to close this because I'm not sure how actionable this is per se. If there's specific bindings issues with the generated JS code that'd be good to have an issue for here. Otherwise if there's expessivity issues with interface types not meshing well with WebGPU then that'd be good to discuss in the interface types repository.
