### ISSUE TITLE
Plans to publish to crates.io?

### ISSUE THREAD

**Issue by Michael-F-Bryan** [bytecodealliance/wit-bindgen#180]
I know this project is still in its infancy and you are still iterating (https://github.com/bytecodealliance/wit-bindgen/issues/157#issuecomment-1040527225), but what would be the roadmap to publishing this project's crates to crates.io?

For context, I'm working on [a `wit-bindgen` generator for WASM3](https://github.com/hotg-ai/wit-bindgen-wasm3), and was hoping to use crates.io dependencies instead of pinning to a specific git commit. 

I think the folks from wasmer might be in the same boat ([wasmerio/wit-bindgen](https://github.com/wasmerio/wit-bindgen)), except they chose to fork the `wit-bindgen` repository when writing their `wit-bindgen-wasmer` generator.

**Comment by syrusakbary** [comment]
200%, it will be incredibly useful to have the crates published

**Comment by alexcrichton** [comment]
Sorry I don't really have much more to add over what's already been said. It's naturally the goal to eventually publish to crates.io but at least personally I do not feel that this is ready. The component model itself is still very much in its infancy and trying to publish and maintain things before everything is ready runs a pretty high likelihood of generating more work for us than would otherwise be necessary. My personal goal is to integrate wit-bindgen well with the component model and today there's lots of pieces in wit-bindgen that could add up to that but as-is it's still pretty far away. 

There's no roadmap at this time, but me and many of my colleagues are focused on moving the component model forward, and `wit-bindgen` is a large part of that.

**Comment by tqwewe** [comment]
Sadly my crate is using wit-bindgen's crates, and I cannot publish my crate since it's using the git urls as dependencies due to this project not being published yet. I hope this could be considered soon, the crates I'm using work great for my case

**Comment by tqwewe** [comment]
Interesting, I'll take a look into it thank you.

**Comment by willemneal** [comment]
> Sorry I don't really have much more to add over what's already been said. It's naturally the goal to eventually publish to crates.io but at least personally I do not feel that this is ready. The component model itself is still very much in its infancy and trying to publish and maintain things before everything is ready runs a pretty high likelihood of generating more work for us than would otherwise be necessary. My personal goal is to integrate wit-bindgen well with the component model and today there's lots of pieces in wit-bindgen that could add up to that but as-is it's still pretty far away.
> 
> There's no roadmap at this time, but me and many of my colleagues are focused on moving the component model forward, and `wit-bindgen` is a large part of that.

@alexcrichton I noticed on crates.io that `wit-parser` is available on crates.io.  Would you be opposed to squatting on this? I think with #245 and a good GH action, we could setup publishing the parser (and perhaps the gen-core crate as well).

I definitely don't want to add more work to you or the rest of the bytecode alliance. Perhaps @Kylebrown9 and myself could handle the publishing aspect (that is ensuring the working GH action and that PRs adhere to conventional commits)?

I'm currently publishing myself, but it would be nice for me and anyone else that wants to build out tools while being 100% comfortable with an unstable API to have an official crate.

**Comment by willemneal** [comment]
That sounds amazing! I would love to help in any way to push this project toward wider adoption!
