### ISSUE TITLE
Implement the `stream` type

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wit-bindgen#233]
https://github.com/bytecodealliance/wit-bindgen/pull/228 added support for parsing the `stream` type. As noted in  https://github.com/bytecodealliance/wit-bindgen/pull/228#pullrequestreview-995028227, there are many `todo!`s left for the implementation in the canonical ABI and bindings implementations.

**Comment by alexcrichton** [comment]
I'm going to close this since there's a lot of open questions about `async`/`stream`/`future`/etc and the syntactic definitions for this are now at the `wit-parser` crate in the `wasm-tools` repository. I expect the next step here is to flesh these out in the component model itself before doing more prototyping work here.
