### ISSUE TITLE
Wit-bindgen support for value imports and value exports

### ISSUE THREAD

**Issue by kulakowski-wasm** [bytecodealliance/wit-bindgen#263]

**Comment by sunfishcode** [comment]
https://github.com/WebAssembly/component-model/pull/71/ describes a specific ABI for value imports and exports.

**Comment by alexcrichton** [comment]
I'm going to close this for now since given the discussion on https://github.com/WebAssembly/component-model/issues/100 the conclusion seems to be that values/start/etc should be postponed to a later date when other aspects are more fleshed out in the component model. To that end I think that short-to-mid-term designs should assume that `value` imports/exports and the `start` function are not going to be implemented and not supported.

In the near-to-mid-term my hope is that `wit-bindgen` can be aligned with the component model as specified so I don't believe that this is going to make the cut since it can't be implemented in Wasmtime at the host level yet due to spec/architectural issues.
