### ISSUE TITLE
Implement the `future` type

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wit-bindgen#270]
https://github.com/bytecodealliance/wit-bindgen/pull/269 adds support for parsing the `future` type. There are many `todo!`s left for the implementation in the canonical ABI and bindings implementations.

**Comment by sunfishcode** [comment]
https://github.com/bytecodealliance/wit-bindgen/issues/270 is an issue tracking the remainder of the implementation for `future`s.

**Comment by alexcrichton** [comment]
One thing I want to note here is that `future`, `stream`, and other async things are not present in the component model spec at this time. To that end I don't believe that this issue is implementable today because it's not clear what it would mean to actually implement the `future` type given that there's no target to implement. I think that work needs to be done to design how `future` and `stream` types would work first before actually implementing them in `wit-bindgen`, although a local fork could of course be used to prototype various design decisions.

**Comment by alexcrichton** [comment]
I'm going to close tis for similar reasons to https://github.com/bytecodealliance/wit-bindgen/issues/233 where work needs to happen upstream first rather than in this repository.
