### ISSUE TITLE
wit_bindgen_wasmtime does not generate the newest wit bindings at build

### ISSUE THREAD

**Issue by Mossaka** [bytecodealliance/wit-bindgen#272]
Consider the following WIT files
```go
use { info } from info

hey: func(i: info) -> info
```

```go
record info {
	infoa: string,
	infob: string,
}
```
The following program compiles and generate the correct bindings for `info` and `hey`  
```rust
let (import, _i) =
    import::Import::instantiate(&mut store, &module, &mut linker, |ctx| &mut ctx.data)?;
let info = import.hey(
    &mut store,
    import::InfoParam {
        infoa: "a",
        infob: "b",
    },
)?;
```

If I add one more field to `info` record, it should fail to compile. 

```go
record info {
	infoa: string,
	infob: string,
        infoc: string,
}
```
However, when I run `cargo build`, I still get my program builds successfully. 
```sh
    Finished dev [unoptimized + debuginfo] target(s) in 1.28s
```

Is this an expected behavior? This is not a big issue since I can make a `build.rs` file to watch for wit file changes and re-build my rust program. 

---
I found that if I combine both WIT files into one file, then adding a new field to `info` record will trigger an error from compiler, saying that the Rust program is missing a field. 

```go
hey: func(i: info) -> info

record info {
	infoa: string,
	infob: string,
	infoc: string,
}
```

```sh
error[E0063]: missing field `infoc` in initializer of `InfoParam<'_>`
  --> src/main.rs:23:9
   |
23 |         import::InfoParam {
   |         ^^^^^^^^^^^^^^^^^ missing `infoc`
```

**Comment by Kylebrown9** [comment]
Can you check to see what code is generated in these cases using `cargo expand`?

**Comment by alexcrichton** [comment]
I believe this bug is roughly [here-ish](https://github.com/bytecodealliance/wit-bindgen/blob/ea71cad5d7f6355cd7cbdb55e3ce40935d387d2f/crates/wasmtime-impl/src/lib.rs#L99-L106) where the source files you pass into the macro are tracked for rebuilds but transitively-depended-on-files are not included in the list of files depended on. That's why it works when the files are merged into one but doesn't work when the files are split.

The fix here would be to change parsing to output the list of files that it consumed. That list of files would then be used instead of only the original input file as the list of files in the proc-macro that are depended on. I think this is also an issue for the rust-to-wasm generator as well.

**Comment by Mossaka** [comment]
I can submit a PR to fix this if no one is working on it @alexcrichton

**Comment by alexcrichton** [comment]
Sure thing, feel free to tackle!

**Comment by alexcrichton** [comment]
For now `use` has been removed and I'll remember to ensure this is fixed when re-added to the Rust macro support.
