### ISSUE TITLE
Difficulty of adding support for a new language

### ISSUE THREAD

**Issue by philpax** [bytecodealliance/wit-bindgen#286]
Hi there! First of all, apologies for using an issue for this - would have opened a discussion but those aren't available.

I'm evaluating the Wasm / wit ecosystem as a plugin / scripting layer, and am happy with the level of support for Rust, but I'm also interested in using other languages as the guest (e.g. import). It would be nice to have export as well, but that's not as important while the Component Model is still being developed.

I'd like to know how difficult it is to write binding generators for languages new to wit-bindgen. The languages of current interest to me are Go, Kotlin and Grain.

Are there any resources I should look at to get a feel for how much work would be involved, or should I just poke around the repo? Cheers!

**Comment by alexcrichton** [comment]
I think the short answer is "it's pretty hard".

The longer-form answer is that having a high-quality bindings generator for something as expansive as the component model is a pretty significant undertaking. You might be able to get 80% of the distance with 20% of the work though in a situation like this. That being said the component model is a moving target that wit-bindgen tries to track but isn't always able to do so. Features like futures/streams are effectively not implemented for any languages today in wit-bindgen.

This all also assumes that the language in question is already well-suited for targeting WebAssembly itself. If it's otherwise difficult to target wasm's features in the native language then that will make writing bindings more difficult.

Finally each language ecosystem has its own tooling to integrate with and often individual decisions need to be made how to best integrate wit-bindgen into each language. For example Rust will likely use procedural macros and/or `cargo component` as a wrapper. This is probably not suitable for Kotlin, for example.

**Comment by philpax** [comment]
Thanks for answering - I really appreciate it!

What you've said makes sense, and agrees with my initial assessment (esp. around futures/streams, which initially took me by surprise, but it's understandable as the Component Model is in such flux). I think it'd be possible to get the 80%/20% solution for those three languages (at least at a glance - they all have pretty good Wasm support), but I think it's probably for the best that I wait until the CM stabilises a little.

I'll close this issue now, but it should hopefully help the next person who has the same question 🙂
