### ISSUE TITLE
allow generating lower_snake_case

### ISSUE THREAD

**Issue by codefromthecrypt** [bytecodealliance/wit-bindgen#403]
it would be nice to define things definable in witx in wit. Notably, lower_snake_case doesn't work.

Ex. this works.
```wit
hello-world: func() -> ()
```
if the filename was foo.wit.md, this results in module "foo" function "hello-world" in the imports.

However, if you use a convention with lower_underscore, similar to old wasi, it breaks.
```wit
hello_world: func() -> ()
```

```bash
$ wit-bindgen host wasmtime-rust -e foo.wit.md 
Error: invalid character in identifier '_'
     --> foo.wit.md:2:1
      |
    2 | hello_world: func() -> ()
      | ^
```

So this prevents us from porting existing witx to wit, until this is made lenient or maybe a name mapping flag is added

**Comment by alexcrichton** [comment]
The `*.wit` syntax is specified in https://github.com/webassembly/component-model ([around here](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md)) which is where this restriction comes from, so if you're interested in changing that it would need to change upstream first.

Otherwise though for some background, the casing and layout of identifiers in `*.wit`, and components, is limited to facilitate generating idiomatic bindings in a wide range of languages. 

Additionally porting `*.witx` one-to-one to `*.wit` will not work since `*.witx` has types like `(@witx pointer $foo)` which the component model does not have. The `*.witx` format was only ever intended to be temporary for a short time and it's just sort of unfortunate it's taken us more time than expected to shore up all this support for the component model.

I'm going to close this for now, but if you're interested in pushing through a change here I'd recommend continuing the discussion in the component-model repository.

**Comment by codefromthecrypt** [comment]
The main point here is that it effects the extern names, which should be something that is language agnostic. I'll raise an issue upstream. thanks

**Comment by codefromthecrypt** [comment]
https://github.com/WebAssembly/component-model/issues/122
