### ISSUE TITLE
Python online generator doesn't work

### ISSUE THREAD

**Issue by Tinche** [bytecodealliance/wit-bindgen#445]
Hello!

It seems the online generator (https://bytecodealliance.github.io/wit-bindgen/) doesn't work for Python with the default contents. The bindings don't change when I select Python from the dropdown. I tried both Chrome and Firefox, on macOs. Not seeing anything in the browser console.

Cheers!

**Comment by alexcrichton** [comment]
Thanks for the report! This is because the `wasmtime-py` generator was moved to the [wasmtime-py repository](https://github.com/bytecodealliance/wasmtime-py) and I forgot to delete it from the demo here. It's being deleted in https://github.com/bytecodealliance/wit-bindgen/pull/439 though so it'll get cleared from the demo soon.
