### ISSUE TITLE
Add support for Serialize, Deserialize, and Default

### ISSUE THREAD

**Issue by autodidaddict** [bytecodealliance/wit-bindgen#554]
The structures that we get from Rust when doing wit-bindgen do not have the `Default` or `Serialize` or `Deserialize` derivations on them. This means that as soon as I attempt to marshal one of these data types somewhere without using a wit function call, I have to manually create my own "mirror types" that have the same structure, but with the serialization attributes on them. Then I have to manually implement either `From` to convert the wit-bindgen type to my type prior to serialization. 

I understand that this kind of activity typically shows up in anti-corruption layers and in an ideal world, the "outside" model and the inside (wit-bindgen) model would never overlap. However, if I have a _lot_ of types and I need to marshal those in and out of my components without making bindgen function calls, I'm stuck redefining every type in my wit world.

Can we get this functionality? If it isn't something that you want on by default, it could be added as a flag to the macro like this:

```rust
wit_bindgen::generate!({
    path: "../wit",
    world: "bankaccount-aggregate",
    serializers: true
});
```

Support for the `serializers` flag could even be hidden behind a feature flag on the wit-bindgen crate.

**Comment by Gearme** [comment]
Fwiw, there's [issue #58 in the component-model repo](https://github.com/WebAssembly/component-model/issues/58) that discusses how to address this kind of issue in a more general way (influencing code generation via anmotations from a WIT document). That said, the discussion seems to have stalled - not least because it's quite a large can of worms: The solution would have to carry across all language generators and parsers.  I'd find it hard to justify solving this issue in a "quick-and-dirty" fashion just for one language. But if you agree that this would be the most sustainable way forward, maybe you can comment/bump there.
That said, I second that it'd be a neat quality of life improvement to be able to specify derive macros at least - whichever way that ends up being implemented.

**Comment by Mossaka** [comment]
Agreed with @Gearme . I am personally interested in exploring how we can add similar annotations to the tinygo/go bindgen.

**Comment by landonxjames** [comment]
I'm working with some fairly large and nested types defined in WIT (see example below) and having trouble deriving `Serialize`/`Deserialize` in the Rust code for them without explicit support from `wit-bindgen`. Using `serde`'s [`remote-derive`](https://serde.rs/remote-derive.html) tends to bottom out whenever a `wit_bindgen::rt::vec::Vec<T>` or other similarly complicated type appears since there are numerous underlying types that don't have the `serde` traits implemented. I could theoretically manually implement both traits myself, but there will be lots of these kinds of types and it would be impractical to implement it for all of them. 

Would a possible interim solution be implementing `Serialize` and `Deserialize` on all the the `wit::rt::*` types so that users can at least get something working with `remote-derive`?

Example of a WIT definition I am working with:
```wit
interface alarm-connector-def {

    record alarm-event {
        event-name: string,
        service: string,
        event-type-code: string,
        event-type-category: string,
        start-time: string,
        end-time: string,
        event-description: event-desc-list,
        affected-entities: entity-list,
    }
    
    type event-desc-list = list<event-description>
    
    record event-description {
        language: string,
        latest-description: string,
    }
    
    type entity-list = list<entity>
    
    record entity{
        entity-value: string,
        tags: list<tag>,
    }
    
    record tag{
        key: string,
        value: string,
    }

    parse: func(input: string) -> alarm-event
}

```

**Comment by thomastaylor312** [comment]
@landonxjames Over in wasmcloud we're running into the same issue with serde. I'm really hoping to get some time to add custom attributes support in the next week or two

**Comment by lann** [comment]
Somewhat relatedly, I have a serde impl here that works with `wasmtime::component::Val`s: https://github.com/lann/wasmtime-component-serde Not directly applicable here but it would be great if the solution here could be compatible with it.
