### ISSUE TITLE
C: import and export of the same resource is not allowed

### ISSUE THREAD

**Issue by Mossaka** [bytecodealliance/wit-bindgen#723]
While I was working on adding runtime tests for the C bindgen, I found that there is a huge limitation at https://github.com/bytecodealliance/wit-bindgen/blob/5572e74449c1d8fcacebe29f927a01924e62a36f/crates/c/src/lib.rs#L186-L189

which prevents the `wit-bindgen`to generate C bindings for most resource related runtime tests. 

I am wondering how much efforts is needed to get this working in C? This work will be needed for Go bindgen to be properly tested to support resources, #696 .

**Comment by alexcrichton** [comment]
I've been wanting to refactor the C generator for quite some time now but I unfortunately don't have a great idea of how to do that. In theory the C generator should be modeled after the Rust on in terms of generating types, but this becomes quite difficult with "anonymous types" like `option<T>`, `tuple<A, B>`, and `result<T, E>`. Right now I think the C generator tries to generate a single anonymous type per world which ends up cascading to this issue. The reason I think is that the C generator tries to assume that each `TypeId` can be mapped to a unique type in C, but that's not correct because the same `TypeId` can be both imported and exported, and especially for resources needs two types.

I think that fixing this will require something along the lines of:

* Much of the destructor logic probably needs refactoring to get a destructor generated immediately when a type is defined rather than much later.
* Type mappings should be per-interface rather than per-world. This primarily applies to anonymous types and how they're printed and deduplicated.

Or... something along those lines. I've never really organized my thoughts here unfortunately. I'm happy to let you take on this work if you'd like, but it will likely and unfortunately be a pretty significant chunk of work.

**Comment by alexcrichton** [comment]
That all makes sense to me yeah. I hope to get to C in the near future myself for other reasons as well, but I do agree with the long-term plan of decoupling Go and C
