### ISSUE TITLE
I do not want component model

### ISSUE THREAD

**Issue by trcrsired** [bytecodealliance/wit-bindgen#833]
No more automatically binding.

**Comment by tschneidereit** [comment]
You're free to disagree with individual technical decisions, or, as in this case, the entire reason for a project's existence. If you want to have anything result from that disagreement, you have to actually explain in detail and with good arguments what you disagree with, and what should be done instead.

If you don't start engaging in a more productive manner, we'll have to ask you to stop engaging at all, instead of disrupting our projects and community.
