### ISSUE TITLE
Panic when function is returning borrowed resource

### ISSUE THREAD

**Issue by andrzejressel** [bytecodealliance/wit-bindgen#907]
`world.wit`

```
package component:test@0.0.1;

world main-world {
    export my-interface;
}
interface my-interface {
    resource my-resource;
    invoke: func() -> borrow<my-resource>;
}
```

`lib.rs`
```
wit_bindgen::generate!({
    world: "main-world"
});
```

error:
```
error: proc macro panicked
 --> src\lib.rs:1:1
  |
1 | / wit_bindgen::generate!({
2 | |     world: "main-world"
3 | | });
  | |__^
  |
  = help: message: assertion failed: mode.lifetime.is_none()
```

I understand that returning borrowed resources is invalid, but I would expect error that points to me to the issue. Same error is also shown when returning struct that contains borrowed resources.

**Comment by alexcrichton** [comment]
Thanks for the report! In the component model returning a borrowed resource is not allowed, so the WIT you've got won't ever actually validate even if the guest were to compile. Not to say there shouldn't be a better error here of course, there very much should be. I mostly wanted to point out that this example will never work, and the issue here is to instead provide a better error message.
