### ISSUE TITLE
might be an error when generating list for tinygo

### ISSUE THREAD

**Issue by wrnlb666** [bytecodealliance/wit-bindgen#924]
I have a very simple interface in wit like so
```wit
export foo: interface {
    record pos {
        x: s64,
        y: s64,
    }
    type bar = list<pos>;
    record line {
        pos: list<pos>,
    }
}
```
after compiling it with `wit-bindgen-cli 0.24.0`, I got this for the types in my `.go` file
```go
type FooPos struct {
  X int64
  Y int64
}

type FooBar = FooPos  // <- I think there's something wrong here, where it should be `[]FooPos`
type FooLine struct {
  Pos []FooPos
}
```
While the `.h` file got generated along seems to be correct
```c
typedef struct foo_pos_t {
  int64_t   x;
  int64_t   y;
} foo_pos_t;

typedef struct foo_bar_t {
  foo_pos_t   *ptr;
  size_t len;
} foo_bar_t;

typedef struct foo_list_pos_t {
  foo_pos_t *ptr;
  size_t len;
} foo_list_pos_t;

typedef struct foo_line_t {
  foo_list_pos_t   pos;
} foo_line_t;
```
## additional information
- I have tried making it `type bar = list<list<pos>>`, and the result is `type FooBar = []FooPos`. So seems like it is always missing a `[]`.

**Comment by Mossaka** [comment]
Hey! Thanks for reporting this bug. 

ugh I am actually not sure what the right fix it and this is becuase in Go generator, we don't actually use `alias types` and whenever the generator sees an alias type, it just resolves that type to it's raw form. For example, `test: func() -> bar` will just resolve `bar` to `[]pos` in the function type signature, so this effectively renders the alias type to be useless in the generated code. 

Perhaps the fix is to just remove the confusing line `type bar = list<pos>;` all altogether. What do you think?

**Comment by wrnlb666** [comment]
The type alias is somewhat wierd, it is trying to work. 
When I have `type bar = pos;`, it will generate `type FooBar = FooPos`. (which is correct)
When I have `type bar = list<pos>;`, it will still generate `type FooBar = FooPos`. (suppose to be `type FooBar = []FooPos`)
But if I have `type bar = list<list<pos>>;`, it will generate `type FooBar = []FooPos`, which suppose to be the result for `type bar = list<pos>;`. (`type FooBar = [][]FooPos` would be correct)


But I think your opinion is right. Type aliasing isn't that important and we can do it ourselves after importing the generated code.
